version: '3.7'

volumes:
  db-data:

networks:
  db:

services:
  prototype:
    container_name: prototype
    build:
      context: .
      dockerfile: docker/prototype.Dockerfile
      args:
        - SCRIPT=JustGegevens.adl # entry script for Ampersand compiler
        - DB_HOST=prototype-db # refers to service below
    environment:
      - AMP_PROTO_ENV_NAME=default # use configured environments (e.g. default, dev, prod)
    volumes:
      - ./:/usr/local/project
    restart: always
    depends_on:
      - prototype-db
    ports:
      - "80:80"
    networks:
      - db
  
  prototype-db:
    restart: always
    image: ampersandtarski/rap3-db
    volumes:
      - db-data:/var/lib/mysql
    container_name: db
    networks:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - prototype-db
    ports:
      - "8080:80"
    networks:
      - db
    environment:
      - PMA_HOST=prototype-db # https://hub.docker.com/r/phpmyadmin/phpmyadmin/