version: '3'

services:
  prototype:
    restart: always
    build:
      context: .
      args:
        ADL_FILE: Analyse.adl

    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./volumes/Wjsg/Analyse/log:/var/www/html/log
 
  db:
    restart: always
    image: ampersandtarski/ampersand-prototype-db

  phptools:
    image: phpmyadmin/phpmyadmin
    ports:
       - "8080:80"
    links:
      - db
