version: '3.7'

volumes:
  db-data:

networks:
  db:

services:
  prototype:
    container_name: prototype
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROTOTYPE_IMAGE_VERSION=latest
    environment:
      - AMPERSAND_DBHOST=prototype-db # refers to service below
    restart: always
    depends_on:
      - prototype-db
    ports:
      - "80:80"
    networks:
      - db
  
  prototype-db:
    container_name: prototype-db
    image: docker.pkg.github.com/ampersandtarski/prototype-db/prototype-db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - prototype-db
    ports:
      - "8080:80"
    networks:
      - db
    environment:
      - PMA_HOST=prototype-db # https://hub.docker.com/r/phpmyadmin/phpmyadmin/